from django.urls import path
from .views import (
    home_view,
    validar_usuario,
    dashboard_view,
    logout_view,
    usuario_view,
    personas_view,
    metodos_pago_view,
    categorias_view,
    marcas_view,
    proveedores_view,
    productos_view,
    pedidos_view,
    pagos_view,
    permisos_view,
    detalle_permisos_view,
    roles_view,
    detalle_roles_view,
    configuracion_view,
)

urlpatterns = [
    path('inicio/', home_view, name='home'),
    path('validar/', validar_usuario, name='validar_usuario'),
    path('inicio_panel/', dashboard_view, name='inicio_panel'),
    path('logout/', logout_view, name='logout'),
    path('usuario/', usuario_view, name='usuario'),
    path('personas/', personas_view, name='personas'),
    path('metodos_pago/', metodos_pago_view, name='metodos_pago'),
    path('categorias/', categorias_view, name='categorias'),
    path('marcas/', marcas_view, name='marcas'),
    path('proveedores/', proveedores_view, name='proveedores'),
    path('productos/', productos_view, name='productos'),
    path('pedidos/', pedidos_view, name='pedidos'),
    path('pagos/', pagos_view, name='pagos'),
    path('permisos/', permisos_view, name='permisos'),
    path('detalle_permisos/', detalle_permisos_view, name='detalle_permisos'),
    path('roles/', roles_view, name='roles'),
    path('detalle_roles/', detalle_roles_view, name='detalle_roles'),
    path('configuracion/', configuracion_view, name='configuracion'),
]
