# Generated by Django 6.0.4 on 2026-04-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='direccion',
        ),
    ]
