# Generated by Django 6.0.4 on 2026-04-21 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0002_remove_personas_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
